### PR TITLE
Update to build_datafile_ftp_directory.pl so it works with the regula…

### PR DESCRIPTION
**Pull request by mn1**
…tion API in release/91

### CODE REVIEW

**Comment by thomasmaurel** [comment]
Looks good thanks

**Comment by thomasmaurel** [comment]
@mn1: I've tried creating the data files symlinks for 91 but it doesn't work for Funcgen, I get the following error:

>         Would have created directory '/nfs/production/panda/ensembl/production/ensemblftp/release-91/data_files/mus_musculus/GRCm38/core/segmentation_file/090/'
> Can't stat /nfs/production/panda/ensembl/production/ensemblftp/data_files/mus_musculus/GRCm38/core/segmentation_file/090: No such file or directory
>  at /homes/ensprod/work/ensembl-production/scripts/datafiles/build_datafile_ftp_directory.pl line 455.

Any idea why we have a "core" in the path?

**Comment by mn1** [comment]
The "core" is added here:

https://github.com/Ensembl/ensembl/blob/release/90/modules/Bio/EnsEMBL/DataFile.pm#L140

**Comment by mn1** [comment]
Not sure how to fix that though

**Comment by thomasmaurel** [comment]
Hmm, I see this is because you are now using the "core" coord_system. Hmm, not an easy fix

**Pull request merged**
