### PR TITLE
Feature/rdf void

### PR DESCRIPTION
**Pull request by avullo**

### CODE REVIEW

**Comment by avullo** [comment]
Has anyone looked into this? This is as much needed as the RDF pipeline itself: the VOID files are a requirements for integration of a release into the SPOT platform.

**Comment by thomasmaurel** [comment]
Thank you.

**Comment by avullo** [comment]
Thanks Thomas,
I've got documentation about how to run it, available at:
https://www.ebi.ac.uk/seqdb/confluence/display/~avullo/RDF+Pipeline+-+Post+Release+Upgrade

Maybe you want to import it in production space?

**Comment by thomasmaurel** [comment]
Thanks Alessandro, I took a copy of your documentation.

**Comment by avullo** [comment]
Good. Another thing: can you wait until I tell before running the script after release? I've got some comments from the SPOT team, the VoID file might need to be reformatted slightly differently. I'll make the necessary changes, then I'll test the submission for ensembl after Aug 15. It that works, you're free to go with ensemblgenomes and then with the two of them for the next releases.

**Comment by thomasmaurel** [comment]
Sure, no worries.

**Pull request merged**
