### PR TITLE
Skipping gtf_to_genepred & gene_pred_check, getting version & directory path for eg!

### PR DESCRIPTION
**Pull request by ckongEbi**
To enable eg! FTP pipeline to use the e! GTF dumper module.

### CODE REVIEW

**Comment by magaliruffier** [comment]
that looks good, thanks for the change
just wondering why you declared the $eg variable outside of the method?

**Comment by nerdstrike** [comment]
Sneaky package global.... functional but not best practice.

**Comment by muffato** [comment]
Indeed, $self->param() is the recommended way of sharing variables between sections of a Runable

**Comment by ckongEbi** [comment]
Sure i'll replace that with use of self->param

**Pull request merged**
