### PR TITLE
store Ontology term synonym xref separately from name

### PR DESCRIPTION
**Pull request by sarahhunt**
Allows searching by synonym via the API.
Requires https://github.com/Ensembl/ensembl/pull/127

### CODE REVIEW

**Comment by magaliruffier** [comment]
Ok, let's see if I understand this correctly
Currently, the OBO file has lines like
synonym: "mutation affecting regulatory region" RELATED []
this gets stored as type=RELATED and name=mutation affecting regulatory region []
Your change would mean the [] at the end of name is stored separately, or rather, whatever information is in there is stored in the dbxref field
Is that correct?

**Comment by sarahhunt** [comment]
That's right. It means exact matching on synonym will be possible.

**Comment by magaliruffier** [comment]
and we remove the trailing quotes
makes sense, I'm happy with that change

**Comment by magaliruffier** [comment]
The change looks fine, can someone from production please accept the PR if you have no objections? @thomasmaurel @amonida @ckongEbi @danstaines

**Comment by thomasmaurel** [comment]
Looks good to me

**Pull request merged**
