### PR TITLE
Ensprod 5803 exon phase

### PR DESCRIPTION
**Pull request by vinay-ebi**
Added exon phase more details in ticket : https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-5803

### CODE REVIEW

**Review by marcoooo — CHANGES_REQUESTED** [review]
I don't think this will be enough, the fetcher is used in many places, did you check its usage across production repo, and potential impact on some existing other dumps? 
Another thing, I believe is if you meant to make it available in search dumps, that might need a modification in the related `Formatter` class.

**Comment by vinay-ebi** [comment]
> I don't think this will be enough, the fetcher is used in many places, did you check its usage across production repo, and potential impact on some existing other dumps? Another thing, I believe is if you meant to make it available in search dumps, that might need a modification in the related `Formatter` class.

fetcher used in  DumpCore pipeline  alone other than unified dumps. 
Unified dumps pipeline uses GeneFetcher.pm module to fetch the gene information  from Raw sql used in BulkFetcher module if we want to add this exon phase information in formater class GeneFetcher we need to query geneinforamtion again with exon phase info. Previously we added CDS and SO terms in Bulkfetcher similar way. I will check the impact of  DumpCore with this changes

**Review by marcoooo — APPROVED** [review]

**Review by marcoooo — APPROVED** [review]

**Review by marcoooo — CHANGES_REQUESTED** [review]
Any chance to fix the build on travis prior to merge?

**Comment by vinay-ebi** [comment]
> Any chance to fix the build on travis prior to merge?

Build failed due to :  missing Copyright [2016-2022] EMBL-European Bioinformatics Institute

**Review by marcoooo — APPROVED** [review]

**Pull request merged**
