### PR TITLE
Feature/strain projection

### PR DESCRIPTION
**Pull request by magaliruffier**

### CODE REVIEW

**Comment by magaliruffier** [comment]
We know this worked for the mouse strains and it is switched off by default, do we want to merge that code in?

**Comment by thomasmaurel** [comment]
@magaliruffier: I have a JIRA ticket for that https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-244. I just need to take your work and implement all your suggestions. I don't have time to look into this at the moment and it's low priority.

**Comment by magaliruffier** [comment]
fair enough, glad you're keeping track better than me!
We have 2 solutions:
- leave it on its branch, hoping there won't be any merge conflicts later on
- merge it in as is, and update the code as/when either of us has more time to look into it

It is your repository, so I'll let you decide, I won't be upset if you close it ;-)

**Comment by thomasmaurel** [comment]
If you won't get upset then I will close it for now ;-). I will review the code changes and push some fresh commits. Thanks a lot for all your work on this.

**Pull request closed without merging**
