### PR TITLE
We should not run xrefs on mus_musculus_casteij, it should be in the …

### PR DESCRIPTION
**Pull request by thomasmaurel**
…antispecies list with the other mouse strains

### CODE REVIEW

**Comment by magaliruffier** [comment]
sorry, I thought castaneus was still a separate species, but it does not have a dedicated species page, I stand corrected
Does this mean we have now lost the former projection xrefs by running the regular xref pipeline?

**Comment by thomasmaurel** [comment]
@magaliruffier: Yes, I am a afraid. @amonida is restoring the release 93 database at the moment.

**Comment by magaliruffier** [comment]
OK, let me know if I can help with this

**Comment by thomasmaurel** [comment]
Thanks @magaliruffier, all fixed now.

**Pull request merged**
